---
- name: Copy last version of nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags:
  - nginx-setup

- name: Ensure default site is absent
  file: 
    name: /etc/nginx/conf.d/default 
    state: absent
  tags:
  - nginx-setup

- name: Clean site folders
  file: 
    name: "{{ item.path }}" 
    state: "{{ item.state }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - { path: '/etc/nginx/sites-enabled', state: 'absent' }
  - { path: '/etc/nginx/sites-enabled', state: 'directory' }
  - { path: '/etc/nginx/sites-available', state: 'absent' }
  - { path: '/etc/nginx/sites-available', state: 'directory' }
  tags:
  - nginx-setup

- name: Copy Vhost to sites-avaible
  template:
    src: "vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.vhost }}"
  with_items: "{{ nginx_sites }}"
  notify: reload nginx
  tags:
  - nginx-vhost

- name: Ensure Vhost are linked in sites-enabled
  file:
    path: "/etc/nginx/sites-enabled/{{ item.vhost }}"
    src: "/etc/nginx/sites-available/{{ item.vhost }}"
    state: link
  with_items: "{{ nginx_sites }}"
  notify: reload nginx
  tags:
  - nginx-vhost
