---
- name: Copy last version of nginx.conf
  copy:
    src: redhat_nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags:
  - nginx-setup

- name: Clean conf.d folder
  file: 
    name: /etc/nginx/conf.d 
    state: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - absent
  - directory
  tags:
  - nginx-setup

- name: Copy Vhost to sites-avaible
  template:
    src: "vhost.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item.vhost }}.conf"
  with_items: "{{ nginx_sites }}"
  notify: reload nginx
  tags:
  - nginx-vhost
