- name: Ensure /var/www exists and have the right owner
  file: 
    path: /var/www 
    state: directory 
    owner: root 
    group: root
  when: ansible_os_family == 'RedHat'
  tags:
  - common

- name: Ensure project folder exists and have the right owner 
  file:
    path: "/var/www/{{ project }}"
    state: directory 
    owner: root 
    group: root
  when: ansible_os_family == 'RedHat'

- name: install basic packages 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
  - epel-release
  when: ansible_os_family == 'RedHat'
  tags:
  - common

- name: Disable firewalld
  service:
    name: firewalld
    state: stoped
    enabled: no

- name: Disable SELinux until next reboot
  shell: stenforce Permissive

