---
galaxy_info:
  author: Paul N. Kniepper Gozalez
  description: Ansible role to deploy web site to VMs.
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: Centos
    versions:
    - 7
  categories:
  - system
dependencies: []
